apiVersion: v1
  kind: pod
  metadata:
    name: myapp-pod
    labels:
    app: myapp
spec:
  containers:
     -name: myapp-container
      image: nginx
      ports:
        containerPort: 80  
---
#------------service nodeport ip------------

apiVersion: v1
kind: service
metadata:
   name: my-service
   lable:
   app: myapp
spec:
   type: NodePort 
   selector:
      app: myapp
   ports:
    -port: 80
     targetPort: 80
     nodePort: 30080    
---
#------------------service cluster IP--------------

apiVersion: v1
kind: service
metadata:
    name: myapp-clusterip
    lable:
      app: myapp-clusterip
spec:
  type: cluster-IP
  selector:
    app: myapp
    ports:
    - port: 80
    targetPort: 80      

---
#----------Loadbalancer service---------

apiVersion: v1
kind: service
matadata:
   name: mypp-loadbalancer
spec:
  type: Loadbalancer  
  selector:
     app: myapp
  ports:
    -port: 80
     targetPort:80 

---
#-----------------------Deployment-------------

apiVersion: apps/v1
kind: Deployment
metadata:
   name: my_deployment
   lables:
     app: myapp
spec:
  replicas: 3
  selector:
   matchLabels:
    app: myapp
  template:
    metadata:
    labels:
    app: myapp  
spec: 
  containers:
     -name: myapp-container
     image: nginx
     ports:
        containerPort: 80
---
#--------------service------------

apiVersion: v1
kind: service
metadata:
   name: my-service
spec:
  type: NodePort
  selector:
    app: myapp 
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080 
---         





